# Generated by Django 3.0.4 on 2020-03-14 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='customers.Customer')),
                ('productorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_productorder', to='products.Product_order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('visible', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('visible', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrdate', models.DateField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('endtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_endtime', to='reservations.Timelist')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_order', to='reservations.Order')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_room', to='reservations.Room')),
                ('starttime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_starttime', to='reservations.Timelist')),
            ],
        ),
    ]
