# Generated by Django 3.0.4 on 2020-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_order_price'),
        ('reservations', '0002_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productorderid',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.Product_order'),
        ),
    ]
