# Generated by Django 3.0.4 on 2020-03-15 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_remove_product_order_price'),
        ('reservations', '0003_auto_20200314_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res',
            name='orderid',
        ),
        migrations.AddField(
            model_name='res',
            name='customerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='customers.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='res',
            name='products',
            field=models.ManyToManyField(to='products.Product_order'),
        ),
        migrations.AddField(
            model_name='res',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
